# Generated by Django 4.2.21 on 2025-05-27 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('statue', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=250, null=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IMC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pouls', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diagnostic', models.CharField(blank=True, max_length=250, null=True)),
                ('constat_consultation', models.CharField(blank=True, max_length=250, null=True)),
                ('examen_demande', models.CharField(blank=True, max_length=250, null=True)),
                ('traitement', models.CharField(blank=True, max_length=250, null=True)),
                ('issue_consultation', models.CharField(blank=True, max_length=250, null=True)),
                ('resultat_examen', models.CharField(blank=True, max_length=250, null=True)),
                ('statue', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sexe', models.CharField(max_length=10)),
                ('lieu_habitation', models.TextField(blank=True)),
                ('numero', models.CharField(max_length=20)),
                ('statut_conjugal', models.CharField(max_length=40)),
                ('groupe_sanguin', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=250, verbose_name='nom')),
                ('prenom', models.CharField(max_length=250)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='Model.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Model.service'),
        ),
        migrations.CreateModel(
            name='ResultatExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='Model.analyse')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('motif', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='Model.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monnaie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(max_length=350)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='Model.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('recu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='Model.recu')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_pre', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='Model.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnotic', models.CharField(blank=True, max_length=550, null=True)),
                ('decision', models.CharField(blank=True, max_length=250, null=True)),
                ('traitement', models.CharField(blank=True, max_length=250, null=True)),
                ('examen', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.CharField(blank=True, max_length=250, null=True)),
                ('statut', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('info_supp', models.CharField(blank=True, max_length=250, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='Model.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Model.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_s', to='Model.service'),
        ),
        migrations.CreateModel(
            name='BulletinExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_pre', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('examen', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='Model.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ArretTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jours', models.IntegerField()),
                ('date_debut', models.DateTimeField()),
                ('nom_med', models.CharField(blank=True, max_length=250, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='Model.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ant_med', models.CharField(blank=True, max_length=250, null=True)),
                ('ant_mal', models.CharField(blank=True, max_length=250, null=True)),
                ('ant_chirur', models.CharField(blank=True, max_length=250, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='Model.patient')),
            ],
        ),
        migrations.AddField(
            model_name='analyse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='Model.patient'),
        ),
    ]
