# Generated by Django 4.2.21 on 2025-05-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='created_at',
        ),
    ]
