# Generated by Django 4.2.21 on 2025-05-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_remove_utilisateur_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roless', to='Model.service'),
        ),
    ]
