# Generated by Django 4.2.21 on 2025-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_alter_role_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
