# Generated by Django 4.2.21 on 2025-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
