# Generated by Django 4.2.21 on 2025-05-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_patient_code_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvousSer', to='Model.service'),
        ),
    ]
